# Демонстрация возможностей ноутбука

### Заголовок

* пункт 1
* пункт 2

In [5]:
x = 1
x = x + 3
print(x)

4


In [6]:
x -= 1
print(x)

3


In [4]:
x -= 0

# Numpy

### Создание массивов

In [7]:
import numpy as np

In [9]:
li = [[28, 1, 0], [22, 1, 5], [1, 28, 1], [28, 0, 2]]
x = np.array(li)

In [10]:
x

array([[28,  1,  0],
       [22,  1,  5],
       [ 1, 28,  1],
       [28,  0,  2]])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
print(x)

[[28  1  0]
 [22  1  5]
 [ 1 28  1]
 [28  0  2]]


In [14]:
x.shape

(4, 3)

In [15]:
x.dtype

dtype('int64')

In [20]:
y = np.zeros(15)
y = y.astype(bool)

In [21]:
y.dtype

dtype('bool')

In [22]:
y.shape

(15,)

In [23]:
y.reshape(3, 5)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [24]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
np.arange(8).reshape(2, 2, 2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Операции с массивами

Операции:
* поэлементные
* матричные
* агрегирующие

In [27]:
x + 1

array([[29,  2,  1],
       [23,  2,  6],
       [ 2, 29,  2],
       [29,  1,  3]])

In [28]:
x

array([[28,  1,  0],
       [22,  1,  5],
       [ 1, 28,  1],
       [28,  0,  2]])

In [29]:
x ** 3

array([[21952,     1,     0],
       [10648,     1,   125],
       [    1, 21952,     1],
       [21952,     0,     8]])

In [30]:
x * 3

array([[84,  3,  0],
       [66,  3, 15],
       [ 3, 84,  3],
       [84,  0,  6]])

In [31]:
a = np.arange(6).reshape(2, 3)
b = np.zeros((2, 3))

In [32]:
a * b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
a + b

array([[0., 1., 2.],
       [3., 4., 5.]])

In [35]:
np.dot(a, b.T)

array([[0., 0.],
       [0., 0.]])

In [36]:
a @ b.T

array([[0., 0.],
       [0., 0.]])

In [37]:
np.linalg.inv(np.eye(5)) # обращение матрицы

array([[ 1., -0., -0.,  0., -0.],
       [ 0.,  1.,  0., -0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [-0., -0., -0.,  1., -0.],
       [ 0.,  0.,  0., -0.,  1.]])

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
x.sum(axis=1)

array([29, 28, 30, 30])

In [47]:
x.argmax(axis=0)

array([0, 2, 1])

In [48]:
np.dot(x, np.array([1, -1, 0]))

array([ 27,  21, -27,  28])

### Индексация

In [52]:
x[0]

array([28,  1,  0])

In [50]:
x[:, 0]

array([28, 22,  1, 28])

In [53]:
x[:, 0] - x[:, 1]

array([ 27,  21, -27,  28])

In [58]:
x[2:4, 1:]

array([[28,  1],
       [ 0,  2]])

In [56]:
x

array([[28,  1,  0],
       [22,  1,  5],
       [ 1, 28,  1],
       [28,  0,  2]])

In [57]:
x[2, 1:]

array([28,  1])

In [70]:
idxs = np.array([True, False, False, True])
x[idxs, :]

array([[28,  1,  0],
       [28,  0,  2]])

In [60]:
idxs

array([ True, False, False,  True])

In [69]:
idxs = np.array([True, True, False])
x[:, idxs]

array([[28,  1],
       [22,  1],
       [ 1, 28],
       [28,  0]])

In [65]:
x[[0, 1], [1, 2]]

array([1, 5])

перемешать строки матрицы

In [74]:
x.shape

(4, 3)

In [71]:
np.arange(x.shape[0])

array([0, 1, 2, 3])

In [72]:
idxs = np.random.permutation(np.arange(x.shape[0]))
idxs

array([2, 0, 1, 3])

In [73]:
x[idxs]

array([[ 1, 28,  1],
       [28,  1,  0],
       [22,  1,  5],
       [28,  0,  2]])

In [77]:
x[:-1] # до послденей строки

array([[28,  1,  0],
       [22,  1,  5],
       [ 1, 28,  1]])

In [78]:
x[::-1] # строки в обратном порядке

array([[28,  0,  2],
       [ 1, 28,  1],
       [22,  1,  5],
       [28,  1,  0]])

In [79]:
# столбцы в обртном порядке
x[:, ::-1]

array([[ 0,  1, 28],
       [ 5,  1, 22],
       [ 1, 28,  1],
       [ 2,  0, 28]])

In [80]:
x[:][::-1] # неправильно

array([[28,  0,  2],
       [ 1, 28,  1],
       [22,  1,  5],
       [28,  1,  0]])

In [82]:
x[1][::-1]

array([ 5,  1, 22])

### Объединение массивов

In [87]:
new = np.array([[30, 1, 0], [15, 15, 0]])
np.vstack((new, x))

array([[30,  1,  0],
       [15, 15,  0],
       [28,  1,  0],
       [22,  1,  5],
       [ 1, 28,  1],
       [28,  0,  2]])

In [ ]:
np.vstack, np.hstack, np.concatenate([...], axis=)

In [88]:
np.concatenate([x, new], axis=0)

array([[28,  1,  0],
       [22,  1,  5],
       [ 1, 28,  1],
       [28,  0,  2],
       [30,  1,  0],
       [15, 15,  0]])

In [92]:
s = x.sum(axis=1)
np.hstack((x, s.reshape(-1, 1)))

array([[28,  1,  0, 29],
       [22,  1,  5, 28],
       [ 1, 28,  1, 30],
       [28,  0,  2, 30]])

In [91]:
x.shape, s.shape

((4, 3), (4,))

In [95]:
s.reshape(-1, 1)

array([[29],
       [28],
       [30],
       [30]])

In [100]:
np.arange(15).reshape(1, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [101]:
v = np.array([1, 2, 3])

In [103]:
v.shape

(3,)

In [102]:
v[np.newaxis, :].shape

(1, 3)

In [104]:
a = np.array([[1, 2], [3, 4]])
b = np.array([1, -1])

In [105]:
a

array([[1, 2],
       [3, 4]])

In [106]:
b

array([ 1, -1])

In [108]:
a * b[:, np.newaxis]

array([[ 1,  2],
       [-3, -4]])

In [109]:
b[:, np.newaxis].shape

(2, 1)

### составить таблицу умножения

In [110]:
a = np.arange(1, 10)
b = np.arange(1, 10)
a, b

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [111]:
a[np.newaxis, :] * b[:, np.newaxis]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [112]:
a * b

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [113]:
a[np.newaxis, :] * b

array([[ 1,  4,  9, 16, 25, 36, 49, 64, 81]])

In [114]:
a[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [115]:
a[np.newaxis, :] + b[:, np.newaxis]

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [116]:
np.dot(a[np.newaxis, :], b[:, np.newaxis])

array([[285]])

In [117]:
np.dot(b[:, np.newaxis], a[np.newaxis, :])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])